### ISSUE TITLE
bit.ly rickroll links not recognized

### ISSUE THREAD

**Issue by zeankundev** [alrudolph/rickrolldetector#1]
I want to request this feature because people often got rickrolled easily with bit.ly or other URL shorteners to hide the rickroll.
https://www.youtube.com/watch?v=dQw4w9WgXcQ
This link recognizes it as a rickroll
https://bit.ly/2VHhZ4I
The rickroll extension doesn't recognize it even though it's a rickroll

**Comment by alrudolph** [comment]
updated, thanks!
